<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ovm.Cqrs\Ovm.Cqrs.csproj" />
    <ProjectReference Include="..\..\src\Ovm.Cqrs.Logging\Ovm.Cqrs.Logging.csproj" />
    <ProjectReference Include="..\..\src\Ovm.Cqrs.EfCore\Ovm.Cqrs.EfCore.csproj" />
  </ItemGroup>

</Project>
