on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - run: ./build.sh ./artifacts

      - uses: actions/upload-artifacts@v4
        with:
          name: packages
          path: artifacts/*
